server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com  #eureka服务端的实例名字
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心,我的职责就是维护实例,不需要去检索实例
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群就是指向其他Eureka
      #defaultZone: http://eureka7002.com:7002/eureka/
      #单机就是7001指向自己
      defaultZone: http://eureka7001.com:7001/eureka/
